AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sqs-example
  
  Sample SAM Template for sqs-example

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt SQSExampleRole.Arn
      CodeUri: processor/
      Handler: index.handler
      Runtime: go1.x
      ReservedConcurrentExecutions: 1
      MemorySize: 128
      Environment:
        Variables:
          TRACKING_TABLE_NAME: !Ref TrackingDynamoDBTable
      Events:
        WorkQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt WorkQueue.Arn
            BatchSize: 10
  ImportFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt SQSExampleRole.Arn
      CodeUri: import/
      Handler: index.handler
      Runtime: go1.x
      MemorySize: 128
      Environment:
        Variables:
          QUEUE_NAME: !GetAtt WorkQueue.QueueName
          TRACKING_TABLE_NAME: !Ref TrackingDynamoDBTable
  WorkQueue:
    Type: AWS::SQS::Queue
  TrackingDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  SQSExampleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - "lambda.amazonaws.com"
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: sqsAllowAll
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: 'arn:aws:sqs:*'
        - PolicyName: dynamodbAllowAll
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: 'arn:aws:dynamodb:*'
        - PolicyName: AllowCloudWatch
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:DescribeLogStreams"
                Resource: "arn:aws:logs:*:*:*"
